env:
  es6: true
  node: true
extends: airbnb-base
plugins:
  - promise
parserOptions:
  sourceType: script
rules:
  linebreak-style: [error, unix]
  max-len: [error, { code: 120, tabWidth: 2 }]
  # Safeguard from accidental use of = instead of === within conditions
  no-cond-assign: [error, except-parens]
  no-multi-spaces: off
  no-param-reassign: [error, { props: false }]
  no-plusplus: off
  no-unused-vars: [warn, { args: none }]
  promise/catch-or-return: error
  promise/no-nesting: error
  promise/no-return-wrap: error
  promise/param-names: error
  strict: [error, global]
